// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/great.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	mi := &file_proto_great_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_great_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_proto_great_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_great_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_great_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_great_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_great_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_great_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_great_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []string               `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameList) Reset() {
	*x = NameList{}
	mi := &file_proto_great_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameList) ProtoMessage() {}

func (x *NameList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_great_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameList.ProtoReflect.Descriptor instead.
func (*NameList) Descriptor() ([]byte, []int) {
	return file_proto_great_proto_rawDescGZIP(), []int{3}
}

func (x *NameList) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type MassageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Massages      []string               `protobuf:"bytes,1,rep,name=massages,proto3" json:"massages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MassageList) Reset() {
	*x = MassageList{}
	mi := &file_proto_great_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassageList) ProtoMessage() {}

func (x *MassageList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_great_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassageList.ProtoReflect.Descriptor instead.
func (*MassageList) Descriptor() ([]byte, []int) {
	return file_proto_great_proto_rawDescGZIP(), []int{4}
}

func (x *MassageList) GetMassages() []string {
	if x != nil {
		return x.Massages
	}
	return nil
}

var File_proto_great_proto protoreflect.FileDescriptor

const file_proto_great_proto_rawDesc = "" +
	"\n" +
	"\x11proto/great.proto\x12\rgreet_service\"\t\n" +
	"\aNoParam\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1e\n" +
	"\bNameList\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\")\n" +
	"\vMassageList\x12\x1a\n" +
	"\bmassages\x18\x01 \x03(\tR\bmassages2\xd2\x02\n" +
	"\fGreetService\x12@\n" +
	"\bSayHello\x12\x16.greet_service.NoParam\x1a\x1c.greet_service.HelloResponse\x12O\n" +
	"\x14SayHelloServerStream\x12\x17.greet_service.NameList\x1a\x1c.greet_service.HelloResponse0\x01\x12Q\n" +
	"\x14SayHelloClientStream\x12\x1b.greet_service.HelloRequest\x1a\x1a.greet_service.MassageList(\x01\x12\\\n" +
	"\x1bSayHelloBidirectionalStream\x12\x1b.greet_service.HelloRequest\x1a\x1c.greet_service.HelloResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_great_proto_rawDescOnce sync.Once
	file_proto_great_proto_rawDescData []byte
)

func file_proto_great_proto_rawDescGZIP() []byte {
	file_proto_great_proto_rawDescOnce.Do(func() {
		file_proto_great_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_great_proto_rawDesc), len(file_proto_great_proto_rawDesc)))
	})
	return file_proto_great_proto_rawDescData
}

var file_proto_great_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_great_proto_goTypes = []any{
	(*NoParam)(nil),       // 0: greet_service.NoParam
	(*HelloRequest)(nil),  // 1: greet_service.HelloRequest
	(*HelloResponse)(nil), // 2: greet_service.HelloResponse
	(*NameList)(nil),      // 3: greet_service.NameList
	(*MassageList)(nil),   // 4: greet_service.MassageList
}
var file_proto_great_proto_depIdxs = []int32{
	0, // 0: greet_service.GreetService.SayHello:input_type -> greet_service.NoParam
	3, // 1: greet_service.GreetService.SayHelloServerStream:input_type -> greet_service.NameList
	1, // 2: greet_service.GreetService.SayHelloClientStream:input_type -> greet_service.HelloRequest
	1, // 3: greet_service.GreetService.SayHelloBidirectionalStream:input_type -> greet_service.HelloRequest
	2, // 4: greet_service.GreetService.SayHello:output_type -> greet_service.HelloResponse
	2, // 5: greet_service.GreetService.SayHelloServerStream:output_type -> greet_service.HelloResponse
	4, // 6: greet_service.GreetService.SayHelloClientStream:output_type -> greet_service.MassageList
	2, // 7: greet_service.GreetService.SayHelloBidirectionalStream:output_type -> greet_service.HelloResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_great_proto_init() }
func file_proto_great_proto_init() {
	if File_proto_great_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_great_proto_rawDesc), len(file_proto_great_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_great_proto_goTypes,
		DependencyIndexes: file_proto_great_proto_depIdxs,
		MessageInfos:      file_proto_great_proto_msgTypes,
	}.Build()
	File_proto_great_proto = out.File
	file_proto_great_proto_goTypes = nil
	file_proto_great_proto_depIdxs = nil
}
